controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    pid_front_left_: { p: 0.0, i: 0.0, d: 0.0}
    pid_front_right_: { p: 0.0, i: 0.0, d: 0.0}
    pid_back_left_: { p: 0.0, i: 0.0, d: 0.0}
    pid_back_right_: { p: 0.0, i: 0.0, d: 0.0}
    Alpha: 0.5
    Wheel_Track: 0.4
    Wheel_Base: 0.4
    Wheel_Radius: 0.05
    Global_Coordinate_Mode: True

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50