<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hero_move">
    <!-- 传动实现:用于连接控制器与关节 -->
    <xacro:macro name="joint_trans" params="joint_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- 每一个驱动轮都需要配置传动装置 -->
    <xacro:joint_trans joint_name="left_front_wheel_joint" />
    <xacro:joint_trans joint_name="right_front_wheel_joint" />
    <xacro:joint_trans joint_name="left_back_wheel_joint" />
    <xacro:joint_trans joint_name="right_back_wheel_joint" />

    <!-- 控制器 -->
    <gazebo>
        <plugin name="gazebo_ros_mecanum_drive" filename="libgazebo_ros_mecanum_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
            <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
            <leftBackJoint>left_back_wheel_joint</leftBackJoint>
            <rightBackJoint>right_back_wheel_joint</rightBackJoint>
            <wheelSeparation>${Wheel_Track * 2}</wheelSeparation> <!-- 车轮间距 -->
            <wheelDiameter>${Wheel_Radius * 2}</wheelDiameter> <!-- 车轮直径 -->
            <wheelBase>${wheel_base}</wheelBase> <!-- 轴距 -->
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic> <!-- 运动控制话题 -->
            <odometryFrame>odom</odometryFrame>
            <odometryTopic>odom</odometryTopic> <!-- 里程计话题 -->
            <robotBaseFrame>base_link</robotBaseFrame> <!-- 根坐标系 -->
        </plugin>
    </gazebo>

</robot>